### ISSUE TITLE
Reports com mesma formatação de entradas.

### ISSUE THREAD

**Issue by ambs** [anacastrosalgado/DACL#19]

**Comment by ambs** [comment]
@anacastrosalgado  vê se te parecem bem os reports.

**Comment by anacastrosalgado** [comment]
Sim, a fonte não é  a mesma, mas serve.

**Comment by anacastrosalgado** [comment]
O itálico não aparece em Note; porquê? ver abrótano

**Comment by ambs** [comment]
Itálico resolvido. 
Para poder expandir categorias vou ter de mudar aqui umas coisas... working on it.

**Comment by ambs** [comment]
"Your wishes are my command"
hihihi
