### ISSUE TITLE
Criar domínio novo

### ISSUE THREAD

**Issue by anacastrosalgado** [anacastrosalgado/DACL#24]
Criar domínio Eletrón. que deve expandir para Eletrónica.

**Comment by ambs** [comment]
Em princípio já funciona

**Comment by ambs** [comment]
Devo alterar automaticamente o seguinte domínio

````
<abbrev text="Electr.">Electricidade</abbrev>
````
para respeitar o AO? (abrev Eletr.)

**Comment by anacastrosalgado** [comment]
Sim, por favor

**Comment by ambs** [comment]
Feito

**Comment by anacastrosalgado** [comment]
Desculpa, não quero ser chata, mas Eletrón. ainda não figura na lista.

**Comment by ambs** [comment]
Não és nada chata. Se não está bem, tens de dizer :) 
Vou ver o que se passou

**Comment by ambs** [comment]
Podes testar de novo, sff?

**Comment by anacastrosalgado** [comment]
Não figura no editor. Não é Eletr. de eletricidade; é eletrón. de eletrónica.
Já agora, Electrotécnia também ficará sem c.

**Comment by ambs** [comment]
Já tenst eletrón.
Entretanto faço a electrotecnia amanhã

Alberto Simões

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ambs** [comment]
Eletrotécnica, feito.

**Comment by anacastrosalgado** [comment]
Validado em fotodíodo.
